<?php
// Property data array
$properties = [
    [
        'id' => 201,
        'image' => 'https://images.unsplash.com/photo-1593487302969-4f8cb523d8a5?w=400&h=300&fit=crop',
        'title' => 'Modern Residential Villa',
        'location' => 'Saravanampatti, Coimbatore',
        'price' => '₹75,00,000',
        'bhk' => '3 BHK',
        'area' => '1800 sq ft',
        'category' => 'Residential House',
        'type' => 'Sale',
        'listedBy' => 'Builder'
    ],
    [
        'id' => 202,
        'image' => 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
        'title' => 'Cozy Family Home',
        'location' => 'RS Puram, Coimbatore',
        'price' => '₹55,00,000',
        'bhk' => '2 BHK',
        'area' => '1300 sq ft',
        'category' => 'Residential House',
        'type' => 'Sale',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 203,
        'image' => 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&h=300&fit=crop',
        'title' => 'Spacious Suburban Home',
        'location' => 'Vadavalli, Coimbatore',
        'price' => '₹65,00,000',
        'bhk' => '3 BHK',
        'area' => '1700 sq ft',
        'category' => 'Residential House',
        'type' => 'Sale',
        'listedBy' => 'Dealer'
    ],
    [
        'id' => 204,
        'image' => 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=400&h=300&fit=crop',
        'title' => 'Luxury Gated House',
        'location' => 'Race Course, Coimbatore',
        'price' => '₹1,20,00,000',
        'bhk' => '1 BHK',
        'area' => '2500 sq ft',
        'category' => 'Residential House',
        'type' => 'Sale',
        'listedBy' => 'Builder'
    ],
    [
        'id' => 205,
        'image' => 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=400&h=300&fit=crop',
        'title' => 'Elegant Family Residence',
        'location' => 'Peelamedu, Coimbatore',
        'price' => '₹95,00,000',
        'bhk' => '2 BHK',
        'area' => '2000 sq ft',
        'category' => 'Residential House',
        'type' => 'Sale',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 301,
        'image' => 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=400&h=300&fit=crop',
        'title' => 'Residential Plot - DTCP Approved',
        'location' => 'Thudiyalur, Coimbatore',
        'price' => '₹35,00,000',
        'bhk' => 'N/A',
        'area' => '1200 sq ft',
        'category' => 'Residential Plots',
        'type' => 'Sale',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 302,
        'image' => 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=400&h=300&fit=crop',
        'title' => 'Prime Corner Plot',
        'location' => 'Vadavalli, Coimbatore',
        'price' => '₹45,00,000',
        'bhk' => 'N/A',
        'area' => '1500 sq ft',
        'category' => 'Residential Plots',
        'type' => 'Sale',
        'listedBy' => 'Dealer'
    ],
    [
        'id' => 303,
        'image' => 'https://images.unsplash.com/photo-1560493676-04071c5f467b?w=400&h=300&fit=crop',
        'title' => 'Spacious Land Parcel',
        'location' => 'Avinashi Road, Coimbatore',
        'price' => '₹1,20,00,000',
        'bhk' => 'N/A',
        'area' => '5000 sq ft',
        'category' => 'Residential Plots',
        'type' => 'Sale',
        'listedBy' => 'Builder'
    ],
    [
        'id' => 304,
        'image' => 'https://images.unsplash.com/photo-1464146072230-91cabc968266?w=400&h=300&fit=crop',
        'title' => 'Gated Community Plot',
        'location' => 'Saravanampatti, Coimbatore',
        'price' => '₹55,00,000',
        'bhk' => 'N/A',
        'area' => '1800 sq ft',
        'category' => 'Residential Plots',
        'type' => 'Sale',
        'listedBy' => 'Builder'
    ],
    [
        'id' => 305,
        'image' => 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&h=300&fit=crop',
        'title' => 'Commercial Resistant Plot',
        'location' => 'Peelamedu, Coimbatore',
        'price' => '₹85,00,000',
        'bhk' => 'N/A',
        'area' => '2500 sq ft',
        'category' => 'Residential Plots',
        'type' => 'Sale',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 401,
        'image' => 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=400&h=300&fit=crop',
        'title' => 'Premium Residential Land',
        'location' => 'Pollachi Road, Coimbatore',
        'price' => '₹60,00,000',
        'bhk' => 'N/A',
        'area' => '1.5 Acres',
        'category' => 'Residential Lands',
        'type' => 'Sale',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 402,
        'image' => 'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?w=400&h=300&fit=crop',
        'title' => 'Developed Residential Land',
        'location' => 'Kinathukadavu, Coimbatore',
        'price' => '₹47,00,000',
        'bhk' => 'N/A',
        'area' => '2 Acres',
        'category' => 'Residential Lands',
        'type' => 'Sale',
        'listedBy' => 'Builder'
    ],
    [
        'id' => 403,
        'image' => 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=400&h=300&fit=crop',
        'title' => 'Corner Residential Plot',
        'location' => 'Vedapatti, Coimbatore',
        'price' => '₹30,00,000',
        'bhk' => 'N/A',
        'area' => '3800 sq ft',
        'category' => 'Residential Lands',
        'type' => 'Sale',
        'listedBy' => 'Dealer'
    ],
    [
        'id' => 404,
        'image' => 'https://images.unsplash.com/photo-1560493676-04071c5f467b?w=400&h=300&fit=crop',
        'title' => 'East Facing Land Parcel',
        'location' => 'Vadavalli, Coimbatore',
        'price' => '₹42,00,000',
        'bhk' => 'N/A',
        'area' => '2000 sq ft',
        'category' => 'Residential Lands',
        'type' => 'Sale',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 405,
        'image' => 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=400&h=300&fit=crop',
        'title' => 'Gated Community Residential Land',
        'location' => 'Saravanampatti, Coimbatore',
        'price' => '₹1,10,00,000',
        'bhk' => 'N/A',
        'area' => '5000 sq ft',
        'category' => 'Residential Lands',
        'type' => 'Sale',
        'listedBy' => 'Dealer'
    ],
    [
        'id' => 501,
        'image' => 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
        'title' => 'Luxury 4 BHK Villa',
        'location' => 'Saravanampatti, Coimbatore',
        'price' => '₹1,20,00,000',
        'bhk' => '4 BHK',
        'area' => '3000 sq ft',
        'category' => 'Residential Villa',
        'type' => 'Sale',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 502,
        'image' => 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=400&h=300&fit=crop',
        'title' => 'Modern Duplex Villa',
        'location' => 'Vadavalli, Coimbatore',
        'price' => '₹1,05,00,000',
        'bhk' => '3 BHK',
        'area' => '2500 sq ft',
        'category' => 'Residential Villa',
        'type' => 'Sale',
        'listedBy' => 'Dealer'
    ],
    [
        'id' => 503,
        'image' => 'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=400&h=300&fit=crop',
        'title' => 'Gated Community Villa',
        'location' => 'Peelamedu, Coimbatore',
        'price' => '₹88,00,000',
        'bhk' => '3 BHK',
        'area' => '2200 sq ft',
        'category' => 'Residential Villa',
        'type' => 'Sale',
        'listedBy' => 'Builder'
    ],
    [
        'id' => 504,
        'image' => 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=400&h=300&fit=crop',
        'title' => 'Independent Villa with Garden',
        'location' => 'Singanallur, Coimbatore',
        'price' => '₹1,50,00,000',
        'bhk' => '4 BHK',
        'area' => '3500 sq ft',
        'category' => 'Residential Villa',
        'type' => 'Sale',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 505,
        'image' => 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400&h=300&fit=crop',
        'title' => 'Modern Villa for Rent',
        'location' => 'Kovaipudur, Coimbatore',
        'price' => '₹55,000/month',
        'bhk' => '3 BHK',
        'area' => '2000 sq ft',
        'category' => 'Residential Villa',
        'type' => 'Rent',
        'listedBy' => 'Dealer'
    ],
    [
        'id' => 601,
        'image' => 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=400&h=300&fit=crop',
        'title' => 'Prime Commercial Land Parcel',
        'location' => 'Mettupalayam Road, Coimbatore',
        'price' => '₹2,50,00,000',
        'bhk' => 'N/A',
        'area' => '4 Acres',
        'category' => 'Commercial Lands',
        'type' => 'Sale',
        'listedBy' => 'Dealer'
    ],
    [
        'id' => 602,
        'image' => 'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?w=400&h=300&fit=crop',
        'title' => 'Development-Ready Land',
        'location' => 'Sulur, Coimbatore',
        'price' => '₹1,45,00,000',
        'bhk' => 'N/A',
        'area' => '2.5 Acres',
        'category' => 'Commercial Lands',
        'type' => 'Sale',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 603,
        'image' => 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=400&h=300&fit=crop',
        'title' => 'Main Road Commercial Land',
        'location' => 'Pollachi Road, Coimbatore',
        'price' => '₹3,85,00,000',
        'bhk' => 'N/A',
        'area' => '3 Acres',
        'category' => 'Commercial Lands',
        'type' => 'Sale',
        'listedBy' => 'Builder'
    ],
    [
        'id' => 604,
        'image' => 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=400&h=300&fit=crop',
        'title' => 'Industrial Zone Land',
        'location' => 'SIDCO, Coimbatore',
        'price' => '₹1,00,00,000',
        'bhk' => 'N/A',
        'area' => '1.5 Acres',
        'category' => 'Commercial Lands',
        'type' => 'Sale',
        'listedBy' => 'Dealer'
    ],
    [
        'id' => 605,
        'image' => 'https://images.unsplash.com/photo-1560493676-04071c5f467b?w=400&h=300&fit=crop',
        'title' => 'Corner Commercial Land',
        'location' => 'Avinashi Road, Coimbatore',
        'price' => '₹4,00,00,000',
        'bhk' => 'N/A',
        'area' => '5 Acres',
        'category' => 'Commercial Lands',
        'type' => 'Sale',
        'listedBy' => 'Owner'
    ],

    // Hotels
    [
        'id' => 1,
        'image' => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
        'title' => 'Luxury Beach Resort Hotel',
        'location' => 'RS Puram, Coimbatore',
        'price' => '₹5,00,00,000',
        'bhk' => 'N/A',
        'area' => '2000 sq ft',
        'category'=>'Hotel',
        'type'=>'Rent',
        'listedBy'=>'Dealer'
    ],
    [
        'id' => 2,
        'image' => 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=400&h=300&fit=crop',
        'title' => 'Boutique Hotel in City Center',
        'location' => 'Gandhipuram, Coimbatore',
        'price' => '₹3,50,00,000',
        'bhk' => 'N/A',
        'area' => '10000 sq ft',
        'category' => 'Hotel',
        'type' => 'Sale',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 3,
        'image' => 'https://images.unsplash.com/photo-1455587734955-081b22074882?w=400&h=300&fit=crop',
        'title' => 'Budget Hotel near Railway',
        'location' => 'Ukkadam, Coimbatore',
        'price' => '₹1,20,00,000',
        'bhk' => 'N/A',
        'area' => '5000 sq ft',
        'category' => 'Hotel',
        'type' => 'Sale',
        'listedBy' => 'Dealer'
    ],
    [
        'id' => 4,
        'image' => 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=400&h=300&fit=crop',
        'title' => 'Heritage Hotel Building',
        'location' => 'Race Course, Coimbatore',
        'price' => '₹80,000/month',
        'bhk' => 'N/A',
        'area' => '8000 sq ft',
        'category' => 'Hotel',
        'type' => 'Rent',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 5,
        'image' => 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=400&h=300&fit=crop',
        'title' => 'Modern Business Hotel',
        'location' => 'Peelamedu, Coimbatore',
        'price' => '₹4,20,00,000',
        'bhk' => 'N/A',
        'area' => '12000 sq ft',
        'category' => 'Hotel',
        'type' => 'Sale',
        'listedBy' => 'Builder'
    ],
    [
        'id' => 701,
        'image' => 'https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=400&h=300&fit=crop',
        'title' => 'Retail Shop in Mall',
        'location' => 'Brookefields, Coimbatore',
        'price' => '₹1,10,000/month',
        'bhk' => 'N/A',
        'area' => '1500 sq ft',
        'category' => 'Commercial Shops',
        'type' => 'Rent',
        'listedBy' => 'Dealer'
    ],
    [
        'id' => 702,
        'image' => 'https://images.unsplash.com/photo-1567958451986-2de427a4a0be?w=400&h=300&fit=crop',
        'title' => 'Main Road Shop for Rent',
        'location' => 'Gandhipuram, Coimbatore',
        'price' => '₹70,000/month',
        'bhk' => 'N/A',
        'area' => '900 sq ft',
        'category' => 'Commercial Shops',
        'type' => 'Rent',
        'listedBy' => 'Builder'
    ],
    [
        'id' => 703,
        'image' => 'https://images.unsplash.com/photo-1528698827591-e19ccd7bc23d?w=400&h=300&fit=crop',
        'title' => 'Ground Floor Retail Space',
        'location' => 'Sai Baba Colony, Coimbatore',
        'price' => '₹95,00,000',
        'bhk' => 'N/A',
        'area' => '800 sq ft',
        'category' => 'Commercial Shops',
        'type' => 'Sale',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 704,
        'image' => 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=400&h=300&fit=crop',
        'title' => 'Prime Location Retail Shop',
        'location' => 'RS Puram, Coimbatore',
        'price' => '₹75,00,000',
        'bhk' => 'N/A',
        'area' => '1200 sq ft',
        'category' => 'Commercial Shops',
        'type' => 'Sale',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 705,
        'image' => 'https://images.unsplash.com/photo-1604328698692-f76ea9498e76?w=400&h=300&fit=crop',
        'title' => 'High Footfall Shopping Space',
        'location' => 'Peelamedu, Coimbatore',
        'price' => '₹90,000/month',
        'bhk' => 'N/A',
        'area' => '1000 sq ft',
        'category' => 'Commercial Shops',
        'type' => 'Rent',
        'listedBy' => 'Dealer'
    ],
    // Hostel & PG
    [
        'id' => 6,
        'image' => 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=400&h=300&fit=crop',
        'title' => 'Girls PG near College',
        'location' => 'Saibaba Colony, Coimbatore',
        'price' => '₹8,000/month',
        'bhk' => 'N/A',
        'area' => '3000 sq ft',
        'category' => 'Hostel & PG',
        'type' => 'Rent',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 7,
        'image' => 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=400&h=300&fit=crop',
        'title' => 'Boys Hostel with Mess',
        'location' => 'Vadavalli, Coimbatore',
        'price' => '₹7,500/month',
        'bhk' => 'N/A',
        'area' => '4000 sq ft',
        'category' => 'Hostel & PG',
        'type' => 'Rent',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 8,
        'image' => 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=300&fit=crop',
        'title' => 'Luxury PG with AC Rooms',
        'location' => 'RS Puram, Coimbatore',
        'price' => '₹12,000/month',
        'bhk' => 'N/A',
        'area' => '2500 sq ft',
        'category' => 'Hostel & PG',
        'type' => 'Rent',
        'listedBy' => 'Dealer'
    ],
    [
        'id' => 9,
        'image' => 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&h=300&fit=crop',
        'title' => 'Working Professionals PG',
        'location' => 'Hopes College, Coimbatore',
        'price' => '₹9,500/month',
        'bhk' => 'N/A',
        'area' => '3500 sq ft',
        'category' => 'Hostel & PG',
        'type' => 'Rent',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 10,
        'image' => 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=400&h=300&fit=crop',
        'title' => 'Spacious Hostel Building',
        'location' => 'Singanallur, Coimbatore',
        'price' => '₹65,00,000',
        'bhk' => 'N/A',
        'area' => '6000 sq ft',
        'category' => 'Hostel & PG',
        'type' => 'Sale',
        'listedBy' => 'Builder'
    ],
    // Shop Commercial
    [
        'id' => 11,
        'image' => 'https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=400&h=300&fit=crop',
        'title' => 'Prime Location Shop',
        'location' => 'Oppanakara Street, Coimbatore',
        'price' => '₹50,000/month',
        'bhk' => 'N/A',
        'area' => '800 sq ft',
        'category' => 'Shop Commercial',
        'type' => 'Rent',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 12,
        'image' => 'https://images.unsplash.com/photo-1604328698692-f76ea9498e76?w=400&h=300&fit=crop',
        'title' => 'Corner Shop in Mall',
        'location' => 'Brookefields, Coimbatore',
        'price' => '₹75,000/month',
        'bhk' => 'N/A',
        'area' => '1000 sq ft',
        'category' => 'Shop Commercial',
        'type' => 'Rent',
        'listedBy' => 'Dealer'
    ],
    [
        'id' => 13,
        'image' => 'https://images.unsplash.com/photo-1567958451986-2de427a4a0be?w=400&h=300&fit=crop',
        'title' => 'Shop for Sale - Main Road',
        'location' => 'Avinashi Road, Coimbatore',
        'price' => '₹85,00,000',
        'bhk' => 'N/A',
        'area' => '1200 sq ft',
        'category' => 'Shop Commercial',
        'type' => 'Sale',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 14,
        'image' => 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=400&h=300&fit=crop',
        'title' => 'Retail Space in Complex',
        'location' => 'Gandhipuram, Coimbatore',
        'price' => '₹60,000/month',
        'bhk' => 'N/A',
        'area' => '900 sq ft',
        'category' => 'Shop Commercial',
        'type' => 'Rent',
        'listedBy' => 'Builder'
    ],
    [
        'id' => 15,
        'image' => 'https://images.unsplash.com/photo-1528698827591-e19ccd7bc23d?w=400&h=300&fit=crop',
        'title' => 'Ground Floor Shop',
        'location' => 'RS Puram, Coimbatore',
        'price' => '₹1,20,00,000',
        'bhk' => 'N/A',
        'area' => '1500 sq ft',
        'category' => 'Shop Commercial',
        'type' => 'Sale',
        'listedBy' => 'Owner'
    ],
    // Warehouse
    [
        'id' => 16,
        'image' => 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=400&h=300&fit=crop',
        'title' => 'Large Industrial Warehouse',
        'location' => 'Kurichi, Coimbatore',
        'price' => '₹1,20,000/month',
        'bhk' => 'N/A',
        'area' => '25000 sq ft',
        'category' => 'Industrial Godown & Warehouse',
        'type' => 'Rent',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 17,
        'image' => 'https://images.unsplash.com/photo-1553413077-190dd305871c?w=400&h=300&fit=crop',
        'title' => 'Climate Controlled Storage',
        'location' => 'Irugur, Coimbatore',
        'price' => '₹85,000/month',
        'bhk' => 'N/A',
        'area' => '2000 sq ft',
        'category' => 'Industrial Godown & Warehouse',
        'type' => 'Rent',
        'listedBy' => 'Dealer'
    ],
    [
        'id' => 18,
        'image' => 'https://images.unsplash.com/photo-1565610222536-ef1d36080cfa?w=400&h=300&fit=crop',
        'title' => 'Warehouse with Loading Dock',
        'location' => 'Chinniyampalayam, Coimbatore',
        'price' => '₹2,50,00,000',
        'bhk' => 'N/A',
        'area' => '30000 sq ft',
        'category' => 'Industrial Godown & Warehouse',
        'type' => 'Sale',
        'listedBy' => 'Builder'
    ],
    [
        'id' => 19,
        'image' => 'https://images.unsplash.com/photo-1587293852726-70cdb56c2866?w=400&h=300&fit=crop',
        'title' => 'Small Storage Unit',
        'location' => 'Peelamedu, Coimbatore',
        'price' => '₹40,000/month',
        'bhk' => 'N/A',
        'area' => '8000 sq ft',
        'category' => 'Industrial Godown & Warehouse',
        'type' => 'Rent',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 20,
        'image' => 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=400&h=300&fit=crop',
        'title' => 'Modern Logistics Center',
        'location' => 'Sathy Road, Coimbatore',
        'price' => '₹3,80,00,000',
        'bhk' => 'N/A',
        'area' => '40000 sq ft',
        'category' => 'Industrial Godown & Warehouse',
        'type' => 'Sale',
        'listedBy' => 'Builder'
    ],
    // Agriculture Land
    [
        'id' => 21,
        'image' => 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=400&h=300&fit=crop',
        'title' => 'Fertile Agricultural Land',
        'location' => 'Pollachi Road, Coimbatore',
        'price' => '₹25,00,000',
        'bhk' => 'N/A',
        'area' => '2 Acres',
        'category' => 'Agriculture Land',
        'type' => 'Sale',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 22,
        'image' => 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=400&h=300&fit=crop',
        'title' => 'Farm Land with Water',
        'location' => 'Anamalai, Coimbatore',
        'price' => '₹45,00,000',
        'bhk' => 'N/A',
        'area' => '5 Acres',
        'category' => 'Agriculture Land',
        'type' => 'Sale',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 23,
        'image' => 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=400&h=300&fit=crop',
        'title' => 'Coconut Plantation Land',
        'location' => 'Mettupalayam Road, Coimbatore',
        'price' => '₹60,00,000',
        'bhk' => 'N/A',
        'area' => '3 Acres',
        'category' => 'Agriculture Land',
        'type' => 'Sale',
        'listedBy' => 'Dealer'
    ],
    [
        'id' => 24,
        'image' => 'https://images.unsplash.com/photo-1560493676-04071c5f467b?w=400&h=300&fit=crop',
        'title' => 'Large Farm Plot',
        'location' => 'Madukkarai, Coimbatore',
        'price' => '₹1,20,00,000',
        'bhk' => 'N/A',
        'area' => '10 Acres',
        'category' => 'Agriculture Land',
        'type' => 'Sale',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 25,
        'image' => 'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?w=400&h=300&fit=crop',
        'title' => 'Organic Farm Land',
        'location' => 'Kinathukadavu, Coimbatore',
        'price' => '₹35,00,000',
        'bhk' => 'N/A',
        'area' => '2.5 Acres',
        'category' => 'Agriculture Land',
        'type' => 'Sale',
        'listedBy' => 'Owner'
    ],
    
    [
        'id' => 101,
        'image' => 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=400&h=300&fit=crop',
        'title' => 'Modern Commercial Building',
        'location' => 'Gandhipuram, Coimbatore',
        'price' => '₹1,00,00,000',
        'bhk' => 'N/A',
        'area' => '10000 sq ft',
        'category' => 'Commercial Building',
        'type' => 'Sale',
        'listedBy' => 'Dealer'
    ],
    [
        'id' => 102,
        'image' => 'https://images.unsplash.com/photo-1560184897-8701e6e0d661?w=400&h=300&fit=crop',
        'title' => 'Downtown Commercial Complex',
        'location' => 'RS Puram, Coimbatore',
        'price' => '₹1,50,00,000',
        'bhk' => 'N/A',
        'area' => '13000 sq ft',
        'category' => 'Commercial Building',
        'type' => 'Sale',
        'listedBy' => 'Builder'
    ],
    [
        'id' => 103,
        'image' => 'https://images.unsplash.com/photo-1573164574398-b0ab875bb1d9?w=400&h=300&fit=crop',
        'title' => 'Prime Commercial Space',
        'location' => 'Peelamedu, Coimbatore',
        'price' => '₹2,00,00,000',
        'bhk' => 'N/A',
        'area' => '15000 sq ft',
        'category' => 'Commercial Building',
        'type' => 'Sale',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 104,
        'image' => 'https://images.unsplash.com/photo-1554415707-6e8cfc93fe23?w=400&h=300&fit=crop',
        'title' => 'Commercial Office Building',
        'location' => 'Avinashi Road, Coimbatore',
        'price' => '₹80,000/month',
        'bhk' => 'N/A',
        'area' => '9000 sq ft',
        'category' => 'Commercial Building',
        'type' => 'Rent',
        'listedBy' => 'Dealer'
    ],
    [
        'id' => 105,
        'image' => 'https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba?w=400&h=300&fit=crop',
        'title' => 'Spacious Commercial Plaza',
        'location' => 'Race Course, Coimbatore',
        'price' => '₹3,50,00,000',
        'bhk' => 'N/A',
        'area' => '20000 sq ft',
        'category' => 'Commercial Building',
        'type' => 'Sale',
        'listedBy' => 'Owner'
    ],
    // Residential Flat
    [
        'id' => 26,
        'image' => 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=400&h=300&fit=crop',
        'title' => 'Spacious 1 BHK Flat',
        'location' => 'Gandhipuram, Coimbatore',
        'price' => '₹15,000/month',
        'bhk' => '1 BHK',
        'area' => '650 sq ft',
        'category' => 'Residential Flat',
        'type' => 'Rent',
        'listedBy' => 'Dealer'
    ],
    [
        'id' => 27,
        'image' => 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=400&h=300&fit=crop',
        'title' => 'Cozy 2 BHK Flat',
        'location' => 'Saibaba Colony, Coimbatore',
        'price' => '₹22,000/month',
        'bhk' => '2 BHK',
        'area' => '1000 sq ft',
        'category' => 'Residential Flat',
        'type' => 'Rent',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 28,
        'image' => 'https://images.unsplash.com/photo-1460317442991-0ec209397118?w=400&h=300&fit=crop',
        'title' => 'Premium 3 BHK Flat',
        'location' => 'RS Puram, Coimbatore',
        'price' => '₹65,00,000',
        'bhk' => '3 BHK',
        'area' => '1500 sq ft',
        'category' => 'Residential Flat',
        'type' => 'Sale',
        'listedBy' => 'Builder'
    ],
    [
        'id' => 29,
        'image' => 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&h=300&fit=crop',
        'title' => 'Affordable 1 BHK',
        'location' => 'Singanallur, Coimbatore',
        'price' => '₹28,00,000',
        'bhk' => '1 BHK',
        'area' => '550 sq ft',
        'category' => 'Residential Flat',
        'type' => 'Sale',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 30,
        'image' => 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=400&h=300&fit=crop',
        'title' => 'Luxury 2 BHK Flat',
        'location' => 'Race Course, Coimbatore',
        'price' => '₹55,00,000',
        'bhk' => '2 BHK',
        'area' => '1250 sq ft',
        'category' => 'Residential Flat',
        'type' => 'Sale',
        'listedBy' => 'Dealer'
    ],
    // Residential Apartment
    [
        'id' => 31,
        'image' => 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=400&h=300&fit=crop',
        'title' => 'Modern 2 BHK Apartment',
        'location' => 'RS Puram, Coimbatore',
        'price' => '₹45,00,000',
        'bhk' => '2 BHK',
        'area' => '1200 sq ft',
        'category' => 'Residential Apartment',
        'type' => 'Sale',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 32,
        'image' => 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=400&h=300&fit=crop',
        'title' => 'Premium 2 BHK Apartment',
        'location' => 'Peelamedu, Coimbatore',
        'price' => '₹55,00,000',
        'bhk' => '2 BHK',
        'area' => '1350 sq ft',
        'category' => 'Residential Apartment',
        'type' => 'Sale',
        'listedBy' => 'Builder'
    ],
    [
        'id' => 33,
        'image' => 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=400&h=300&fit=crop',
        'title' => 'Spacious 3 BHK Apartment',
        'location' => 'Saravanampatti, Coimbatore',
        'price' => '₹75,00,000',
        'bhk' => '3 BHK',
        'area' => '1800 sq ft',
        'category' => 'Residential Apartment',
        'type' => 'Sale',
        'listedBy' => 'Builder'
    ],
    [
        'id' => 34,
        'image' => 'https://images.unsplash.com/photo-1567496898669-ee935f5f647a?w=400&h=300&fit=crop',
        'title' => 'Compact 1 BHK Apartment',
        'location' => 'Hopes College, Coimbatore',
        'price' => '₹18,000/month',
        'bhk' => '1 BHK',
        'area' => '700 sq ft',
        'category' => 'Residential Apartment',
        'type' => 'Rent',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 35,
        'image' => 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=400&h=300&fit=crop',
        'title' => 'Gated Community 3 BHK',
        'location' => 'Vadavalli, Coimbatore',
        'price' => '₹85,00,000',
        'bhk' => '3 BHK',
        'area' => '2000 sq ft',
        'category' => 'Residential Apartment',
        'type' => 'Sale',
        'listedBy' => 'Builder'
    ],
    // Villa
    [
        'id' => 36,
        'image' => 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
        'title' => 'Luxury 3 BHK Villa',
        'location' => 'Saravanampatti, Coimbatore',
        'price' => '₹85,00,000',
        'bhk' => '3 BHK',
        'area' => '2000 sq ft',
        'category' => 'Villa',
        'type' => 'Sale',
        'listedBy' => 'Builder'
    ],
    [
        'id' => 37,
        'image' => 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=400&h=300&fit=crop',
        'title' => 'Premium 3 BHK Villa',
        'location' => 'Thudiyalur, Coimbatore',
        'price' => '₹1,20,00,000',
        'bhk' => '3 BHK',
        'area' => '2500 sq ft',
        'category' => 'Villa',
        'type' => 'Sale',
        'listedBy' => 'Builder'
    ],
    [
        'id' => 38,
        'image' => 'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=400&h=300&fit=crop',
        'title' => 'Duplex Villa with Garden',
        'location' => 'Avinashi Road, Coimbatore',
        'price' => '₹95,00,000',
        'bhk' => '3 BHK',
        'area' => '2200 sq ft',
        'category' => 'Villa',
        'type' => 'Sale',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 39,
        'image' => 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=400&h=300&fit=crop',
        'title' => 'Independent 2 BHK Villa',
        'location' => 'Kuniyamuthur, Coimbatore',
        'price' => '₹65,00,000',
        'bhk' => '2 BHK',
        'area' => '1600 sq ft',
        'category' => 'Villa',
        'type' => 'Sale',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 40,
        'image' => 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400&h=300&fit=crop',
        'title' => 'Modern Villa for Rent',
        'location' => 'Vadavalli, Coimbatore',
        'price' => '₹45,000/month',
        'bhk' => '3 BHK',
        'area' => '2000 sq ft',
        'category' => 'Villa',
        'type' => 'Rent',
        'listedBy' => 'Dealer'
    ],
    [
        'id' => 1001,
        'image' => 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=400&h=300&fit=crop',
        'title' => 'Grand City Marriage Hall',
        'location' => 'Ukkadam, Coimbatore',
        'price' => '₹2,80,00,000',
        'bhk' => 'N/A',
        'area' => '12000 sq ft',
        'category' => 'Marriage Hall',
        'type' => 'Sale',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 1002,
        'image' => 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop',
        'title' => 'Premium Banquet Hall',
        'location' => 'RS Puram, Coimbatore',
        'price' => '₹1,90,00,000',
        'bhk' => 'N/A',
        'area' => '8000 sq ft',
        'category' => 'Marriage Hall',
        'type' => 'Sale',
        'listedBy' => 'Dealer'
    ],
    [
        'id' => 1003,
        'image' => 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=400&h=300&fit=crop',
        'title' => 'AC Marriage Hall',
        'location' => 'Peelamedu, Coimbatore',
        'price' => '₹3,40,00,000',
        'bhk' => 'N/A',
        'area' => '14000 sq ft',
        'category' => 'Marriage Hall',
        'type' => 'Sale',
        'listedBy' => 'Builder'
    ],
    [
        'id' => 1004,
        'image' => 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=400&h=300&fit=crop',
        'title' => 'Traditional Hall for Functions',
        'location' => 'Vadavalli, Coimbatore',
        'price' => '₹60,000/month',
        'bhk' => 'N/A',
        'area' => '9000 sq ft',
        'category' => 'Marriage Hall',
        'type' => 'Rent',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 1005,
        'image' => 'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=400&h=300&fit=crop',
        'title' => 'Budget Mini Marriage Hall',
        'location' => 'Singanallur, Coimbatore',
        'price' => '₹45,000/month',
        'bhk' => 'N/A',
        'area' => '5000 sq ft',
        'category' => 'Marriage Hall',
        'type' => 'Rent',
        'listedBy' => 'Dealer'
    ],
    // Plot/Land
    [
        'id' => 41,
        'image' => 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=400&h=300&fit=crop',
        'title' => 'Residential Plot - DTCP',
        'location' => 'Thudiyalur, Coimbatore',
        'price' => '₹35,00,000',
        'bhk' => 'N/A',
        'area' => '1200 sq ft',
        'category' => 'Plot/Land',
        'type' => 'Sale',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 42,
        'image' => 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=400&h=300&fit=crop',
        'title' => 'Corner Plot - Prime',
        'location' => 'Vadavalli, Coimbatore',
        'price' => '₹45,00,000',
        'bhk' => 'N/A',
        'area' => '1500 sq ft',
        'category' => 'Plot/Land',
        'type' => 'Sale',
        'listedBy' => 'Dealer'
    ],
    [
        'id' => 43,
        'image' => 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=400&h=300&fit=crop',
        'title' => 'Large Land Parcel',
        'location' => 'Avinashi Road, Coimbatore',
        'price' => '₹1,20,00,000',
        'bhk' => 'N/A',
        'area' => '5000 sq ft',
        'category' => 'Plot/Land',
        'type' => 'Sale',
        'listedBy' => 'Builder'
    ],
    [
        'id' => 44,
        'image' => 'https://images.unsplash.com/photo-1464146072230-91cabc968266?w=400&h=300&fit=crop',
        'title' => 'Gated Community Plot',
        'location' => 'Saravanampatti, Coimbatore',
        'price' => '₹55,00,000',
        'bhk' => 'N/A',
        'area' => '1800 sq ft',
        'category' => 'Plot/Land',
        'type' => 'Sale',
        'listedBy' => 'Builder'
    ],
    [
        'id' => 45,
        'image' => 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&h=300&fit=crop',
        'title' => 'Commercial Land',
        'location' => 'Peelamedu, Coimbatore',
        'price' => '₹85,00,000',
        'bhk' => 'N/A',
        'area' => '2500 sq ft',
        'category' => 'Plot/Land',
        'type' => 'Sale',
        'listedBy' => 'Owner'
    ],
    // Office Space
    [
        'id' => 46,
        'image' => 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=400&h=300&fit=crop',
        'title' => 'Modern Office Space',
        'location' => 'RS Puram, Coimbatore',
        'price' => '₹65,000/month',
        'bhk' => 'N/A',
        'area' => '1500 sq ft',
        'category' => 'Commercial Office',
        'type' => 'Rent',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 47,
        'image' => 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=400&h=300&fit=crop',
        'title' => 'IT Park Office',
        'location' => 'Saravanampatti, Coimbatore',
        'price' => '₹85,000/month',
        'bhk' => 'N/A',
        'area' => '15000 sq ft',
        'category' => 'Commercial Office',
        'type' => 'Sale',
        'listedBy' => 'Builder'
    ],
        [
        'id' => 48,
        'image' => 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=400&h=300&fit=crop',
        'title' => 'Premium Office for Sale',
        'location' => 'Gandhipuram, Coimbatore',
        'price' => '₹1,50,00,000',
        'bhk' => 'N/A',
        'area' => '3000 sq ft',
        'category' => 'Commercial Office',
        'type' => 'Sale',
        'listedBy' => 'Builder'
    ],
    [
        'id' => 49,
        'image' => 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=400&h=300&fit=crop',
        'title' => 'Startup Office Space',
        'location' => 'Peelamedu, Coimbatore',
        'price' => '₹35,000/month',
        'bhk' => 'N/A',
        'area' => '800 sq ft',
        'category' => 'Commercial Office',
        'type' => 'Rent',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 50,
        'image' => 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=400&h=300&fit=crop',
        'title' => 'Corporate Office Building',
        'location' => 'Avinashi Road, Coimbatore',
        'price' => '₹2,50,00,000',
        'bhk' => 'N/A',
        'area' => '5000 sq ft',
        'category' => 'Commercial Office',
        'type' => 'Sale',
        'listedBy' => 'Builder'
    ],
    [
        'id' => 901,
        'image' => 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=400&h=300&fit=crop',
        'title' => 'Coconut Agriculture Farm',
        'location' => 'Karamadai, Coimbatore',
        'price' => '₹75,00,000',
        'bhk' => 'N/A',
        'area' => '5 Acres',
        'category' => 'Agriculture Farm',
        'type' => 'Sale',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 902,
        'image' => 'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?w=400&h=300&fit=crop',
        'title' => 'Organic Banana Farm',
        'location' => 'Pollachi, Coimbatore',
        'price' => '₹1,15,00,000',
        'bhk' => 'N/A',
        'area' => '10 Acres',
        'category' => 'Agriculture Farm',
        'type' => 'Sale',
        'listedBy' => 'Builder'
    ],
    [
        'id' => 903,
        'image' => 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=400&h=300&fit=crop',
        'title' => 'Irrigated Farm Land',
        'location' => 'Kinathukadavu, Coimbatore',
        'price' => '₹68,00,000',
        'bhk' => 'N/A',
        'area' => '4 Acres',
        'category' => 'Agriculture Farm',
        'type' => 'Sale',
        'listedBy' => 'Dealer'
    ],
    [
        'id' => 904,
        'image' => 'https://images.unsplash.com/photo-1560493676-04071c5f467b?w=400&h=300&fit=crop',
        'title' => 'Farm on State Highway',
        'location' => 'Anamalai, Coimbatore',
        'price' => '₹90,00,000',
        'bhk' => 'N/A',
        'area' => '6.7 Acres',
        'category' => 'Agriculture Farm',
        'type' => 'Sale',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 905,
        'image' => 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=400&h=300&fit=crop',
        'title' => 'Private Mango Farm',
        'location' => 'Sathy Road, Coimbatore',
        'price' => '₹50,00,000',
        'bhk' => 'N/A',
        'area' => '3 Acres',
        'category' => 'Agriculture Farm',
        'type' => 'Sale',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 1101,
        'image' => 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&h=300&fit=crop',
        'title' => 'Luxury Apartment Block',
        'location' => 'Race Course, Coimbatore',
        'price' => '₹1,80,00,000',
        'bhk' => 'N/A',
        'area' => '8000 sq ft',
        'category' => 'Residential Building',
        'type' => 'Sale',
        'listedBy' => 'Builder'
    ],
    [
        'id' => 1102,
        'image' => 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=400&h=300&fit=crop',
        'title' => 'Modern Family Building',
        'location' => 'Gandhipuram, Coimbatore',
        'price' => '₹85,00,000',
        'bhk' => 'N/A',
        'area' => '9000 sq ft',
        'category' => 'Residential Building',
        'type' => 'Sale',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 1103,
        'image' => 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=400&h=300&fit=crop',
        'title' => 'Compact Residential Complex',
        'location' => 'RS Puram, Coimbatore',
        'price' => '₹1,10,00,000',
        'bhk' => 'N/A',
        'area' => '7000 sq ft',
        'category' => 'Residential Building',
        'type' => 'Sale',
        'listedBy' => 'Dealer'
    ],
    [
        'id' => 1104,
        'image' => 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=400&h=300&fit=crop',
        'title' => 'Family Apartments',
        'location' => 'Peelamedu, Coimbatore',
        'price' => '₹70,000/month',
        'bhk' => 'N/A',
        'area' => '6000 sq ft',
        'category' => 'Residential Building',
        'type' => 'Rent',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 1105,
        'image' => 'https://images.unsplash.com/photo-1460317442991-0ec209397118?w=400&h=300&fit=crop',
        'title' => 'Premium Urban Residence',
        'location' => 'Vadavalli, Coimbatore',
        'price' => '₹1,55,00,000',
        'bhk' => 'N/A',
        'area' => '7500 sq ft',
        'category' => 'Residential Building',
        'type' => 'Sale',
        'listedBy' => 'Builder'
    ],
    [
        'id' => 1301,
        'image' => 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=400&h=300&fit=crop',
        'title' => 'Popular Foods Outlet',
        'location' => 'Brookefields, Coimbatore',
        'price' => '₹70,000/month',
        'bhk' => 'N/A',
        'area' => '1800 sq ft',
        'category' => 'Restaurant Foods & Drinks',
        'type' => 'Rent',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 1302,
        'image' => 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=400&h=300&fit=crop',
        'title' => 'Bar & Cafe for Sale',
        'location' => 'Peelamedu, Coimbatore',
        'price' => '₹90,00,000',
        'bhk' => 'N/A',
        'area' => '2400 sq ft',
        'category' => 'Restaurant Foods & Drinks',
        'type' => 'Sale',
        'listedBy' => 'Dealer'
    ],
    [
        'id' => 1303,
        'image' => 'https://images.unsplash.com/photo-1528698827591-e19ccd7bc23d?w=400&h=300&fit=crop',
        'title' => 'Fast Food Corner',
        'location' => 'Singanallur, Coimbatore',
        'price' => '₹32,000/month',
        'bhk' => 'N/A',
        'area' => '950 sq ft',
        'category' => 'Restaurant Foods & Drinks',
        'type' => 'Rent',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 1304,
        'image' => 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&h=300&fit=crop',
        'title' => 'Bakery on Main Road',
        'location' => 'RS Puram, Coimbatore',
        'price' => '₹60,00,000',
        'bhk' => 'N/A',
        'area' => '1200 sq ft',
        'category' => 'Restaurant Foods & Drinks',
        'type' => 'Sale',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 1305,
        'image' => 'https://images.unsplash.com/photo-1604328698692-f76ea9498e76?w=400&h=300&fit=crop',
        'title' => 'Cafe Franchise Opportunity',
        'location' => 'Gandhipuram, Coimbatore',
        'price' => '₹75,000/month',
        'bhk' => 'N/A',
        'area' => '1100 sq ft',
        'category' => 'Restaurant Foods & Drinks',
        'type' => 'Rent',
        'listedBy' => 'Builder'
    ],
    [
        'id' => 1201,
        'image' => 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=400&h=300&fit=crop',
        'title' => 'Roof Garden Family Restaurant',
        'location' => 'RS Puram, Coimbatore',
        'price' => '₹55,000/month',
        'bhk' => 'N/A',
        'area' => '2800 sq ft',
        'category' => 'Residential Restaurant',
        'type' => 'Rent',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 1202,
        'image' => 'https://images.unsplash.com/photo-1528698827591-e19ccd7bc23d?w=400&h=300&fit=crop',
        'title' => 'Multi Cuisine Dining',
        'location' => 'Peelamedu, Coimbatore',
        'price' => '₹1,25,00,000',
        'bhk' => 'N/A',
        'area' => '4500 sq ft',
        'category' => 'Residential Restaurant',
        'type' => 'Sale',
        'listedBy' => 'Builder'
    ],
    [
        'id' => 1203,
        'image' => 'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=400&h=300&fit=crop',
        'title' => 'Fine Dining with Stay',
        'location' => 'Vadavalli, Coimbatore',
        'price' => '₹90,00,000',
        'bhk' => 'N/A',
        'area' => '3500 sq ft',
        'category' => 'Residential Restaurant',
        'type' => 'Sale',
        'listedBy' => 'Dealer'
    ],
    [
        'id' => 1204,
        'image' => 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=400&h=300&fit=crop',
        'title' => 'Traditional South Indian Restaurant',
        'location' => 'Hopes College, Coimbatore',
        'price' => '₹36,000/month',
        'bhk' => 'N/A',
        'area' => '2200 sq ft',
        'category' => 'Residential Restaurant',
        'type' => 'Rent',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 1205,
        'image' => 'https://images.unsplash.com/photo-1567958451986-2de427a4a0be?w=400&h=300&fit=crop',
        'title' => 'Big Family Restaurant',
        'location' => 'Gandhipuram, Coimbatore',
        'price' => '₹1,40,00,000',
        'bhk' => 'N/A',
        'area' => '5000 sq ft',
        'category' => 'Residential Restaurant',
        'type' => 'Sale',
        'listedBy' => 'Dealer'
    ],
    [
        'id' => 801,
        'image' => 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?w=400&h=300&fit=crop',
        'title' => 'Large Industrial Manufacturing Unit',
        'location' => 'SIDCO Industrial Estate, Coimbatore',
        'price' => '₹3,80,00,000',
        'bhk' => 'N/A',
        'area' => '32000 sq ft',
        'category' => 'Industrial Building',
        'type' => 'Sale',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 802,
        'image' => 'https://images.unsplash.com/photo-1553413077-190dd305871c?w=400&h=300&fit=crop',
        'title' => 'Warehouse & Plant Facility',
        'location' => 'Irugur, Coimbatore',
        'price' => '₹2,10,00,000',
        'bhk' => 'N/A',
        'area' => '21000 sq ft',
        'category' => 'Industrial Building',
        'type' => 'Sale',
        'listedBy' => 'Dealer'
    ],
    [
        'id' => 803,
        'image' => 'https://images.unsplash.com/photo-1556740761-1a741367b93e?w=400&h=300&fit=crop',
        'title' => 'Industrial Shed with Office',
        'location' => 'Kurichi, Coimbatore',
        'price' => '₹1,65,00,000',
        'bhk' => 'N/A',
        'area' => '15000 sq ft',
        'category' => 'Industrial Building',
        'type' => 'Sale',
        'listedBy' => 'Builder'
    ],
    [
        'id' => 804,
        'image' => 'https://images.unsplash.com/photo-1573164713347-df1e1470b7b6?w=400&h=300&fit=crop',
        'title' => 'Furnished Industrial Space',
        'location' => 'Avinashi Road, Coimbatore',
        'price' => '₹1,20,000/month',
        'bhk' => 'N/A',
        'area' => '18000 sq ft',
        'category' => 'Industrial Building',
        'type' => 'Rent',
        'listedBy' => 'Owner'
    ],
    [
        'id' => 805,
        'image' => 'https://images.unsplash.com/photo-1579613832129-626bda2373e3?w=400&h=300&fit=crop',
        'title' => 'Industrial Shed for Lease',
        'location' => 'Pappampatti, Coimbatore',
        'price' => '₹80,000/month',
        'bhk' => 'N/A',
        'area' => '11000 sq ft',
        'category' => 'Industrial Building',
        'type' => 'Rent',
        'listedBy' => 'Dealer'
    ]
];
$categories = [
    'Residential House',
    'Residential Plots',
    'Residential Lands',
    'Residential Villa',
    'Commercial Lands',
    'Commercial Shops',
    'Commercial Office',
    'Hotel',
    'Hostel & PG',
    'Shop Commercial',
    'Industrial Godown & Warehouse',
    'Agriculture Land',
    'Commercial Building',
    'Industrial Building',
    'Marriage Hall',
    'Residential Building',
    'Residential Flat',
    'Residential Apartment',
    'Agriculture Farm',
    'Restaurant Foods & Drinks',
    'Plot/Land'
    
];

$propertiesJson = json_encode($properties);
$categoriesJson = json_encode($categories);

// Get category from URL parameter
$selectedCategory = isset($_GET['category']) ? $_GET['category'] : '';
?>

